### ISSUE TITLE
missing NOTEEVENTS.csv file ?

### ISSUE THREAD

**Issue by thangld201** [bsinghpratap/ScAN#1]
Hi @bsinghpratap, thank you very much for the works!

To parse the data as in get_HADM_files.py, we need this NOTEEVENTS.csv file but its not in the repo. Can you upload it ?

**Comment by bsinghpratap** [comment]
Hi @thangld201, since `NOTEEVENTS.csv` is part of MIMIC dataset we cannot upload it on GitHub. You would have to access it through physionet.org by applying for access to the MIMIC-III dataset. thanks.
